### ISSUE TITLE
PATCH requests?

### ISSUE THREAD

**Issue by patsplat** [hgoebl/DavidWebb#20]
Would supporting PATCH requests be a valid PR?

**Comment by hgoebl** [comment]
There is already a branch containing PATCH. -> https://github.com/hgoebl/DavidWebb/tree/method_PATCH

The problem is, that HttpURLConnection doesn't support this method. If the underlying implementation is OkHttp, then it should work. It might also work on newer Android versions, because AFAIK they have OkHttp under the hood.

TL;DR if you have a working solution, of course this PR would be welcome!

**Comment by patsplat** [comment]
Fair enough.  Lived without it for long enough, closing the issue for inactivity.
